#!/usr/bin/env bash
# ============================================================================
# S5 Aligned Experiment — one-shot environment setup for Ubuntu cloud host.
# ============================================================================
# Idempotent: safe to re-run. Run once at session start, then `bash run_all.sh`.
#
# Steps:
#   1. apt-get install jdk-8 + jdk-11 + maven + python3 + tools
#   2. detect JVM paths and write them into .env
#   3. pip install pandas numpy scipy statsmodels
#   4. download GenMorph Zenodo replication package (~80 MB, idempotent)
#   5. build GAssert fat-jar if absent

set -euo pipefail

echo "=== S5 aligned experiment setup ==="

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# ----------------------------------------------------------------------------
# 1. System packages
# ----------------------------------------------------------------------------
echo "[1/5] Installing system packages..."

# 移除已知失效的 PPA，防止 apt-get update 报错退出

sudo rm -f /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-*.list \
           /etc/apt/sources.list.d/ondrej-ubuntu-php-*.list 2>/dev/null || true

sudo apt-get update -y -qq
sudo apt-get install -y -qq \
    openjdk-8-jdk \
    openjdk-11-jdk \
    maven \
    python3-pip \
    wget unzip git curl ca-certificates

# ----------------------------------------------------------------------------
# 2. Detect JVM paths and rewrite .env
# ----------------------------------------------------------------------------
echo "[2/5] Detecting JVM paths..."
JAVA8=$(find /usr/lib/jvm -maxdepth 1 -type d \( -name "java-8*" -o -name "*openjdk-8*" \) 2>/dev/null | head -1)
JAVA11=$(find /usr/lib/jvm -maxdepth 1 -type d \( -name "java-11*" -o -name "*openjdk-11*" \) 2>/dev/null | head -1)
[[ -z "$JAVA8"  ]] && { echo "FATAL: JDK 8 not found";  exit 1; }
[[ -z "$JAVA11" ]] && { echo "FATAL: JDK 11 not found"; exit 1; }
echo "  JDK 8  → $JAVA8"
echo "  JDK 11 → $JAVA11"

# Rewrite .env with detected paths so subsequent scripts pick them up
cat > "$REPO_ROOT/.env" <<EOF
# Auto-generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
JAVA8=$JAVA8
JAVA11=$JAVA11
JAVA_HOME=$JAVA8

GENMORPH=/tmp/genmorph_pilot/genmorph_full/genmorph
GENMORPH_EVAL=/tmp/genmorph_pilot/evaluation/evaluation
GENMORPH_MRS=/tmp/genmorph_pilot/mrs/mrs

GASSERT_JAR=/tmp/genmorph_pilot/genmorph_full/genmorph/build/libs/GAssert-1.0-SNAPSHOT-all.jar
PITEST_WRAPPER=/tmp/genmorph_pilot/genmorph_full/genmorph/pitest-wrapper-1.7.4.jar
RANDOOP_JAR=/tmp/genmorph_pilot/genmorph_full/genmorph/randoop-all-4.3.0.jar
EVOSUITE_JAR=/tmp/genmorph_pilot/genmorph_full/genmorph/evosuite-1.1.0.jar

S5_ROOT=$REPO_ROOT
SEED=11
SUBJECTS=all
EOF

# ----------------------------------------------------------------------------
# 3. Python deps
# ----------------------------------------------------------------------------
echo "[3/5] Installing Python packages..."
pip3 install --quiet --user pandas numpy scipy statsmodels

# ----------------------------------------------------------------------------
# 4. GenMorph Zenodo replication package
# ----------------------------------------------------------------------------
echo "[4/5] Fetching GenMorph Zenodo data (~80 MB)..."
mkdir -p /tmp/genmorph_pilot
cd /tmp/genmorph_pilot
ZENODO=https://zenodo.org/records/10067096/files
for ZIP in evaluation.zip mrs.zip genmorph.zip; do
    if [[ -f "$ZIP" ]]; then
        echo "  $ZIP cached, skip"
    else
        echo "  fetching $ZIP..."
        wget -q --no-check-certificate "$ZENODO/$ZIP"
    fi
done
[[ -d evaluation    ]] || unzip -q evaluation.zip
[[ -d mrs           ]] || unzip -q mrs.zip
[[ -d genmorph_full ]] || unzip -q genmorph.zip -d genmorph_full

# ----------------------------------------------------------------------------
# 5. Build GAssert jar
# ----------------------------------------------------------------------------
echo "[5/5] Building GAssert jar (if absent)..."
GENMORPH=/tmp/genmorph_pilot/genmorph_full/genmorph
GASSERT_JAR=$GENMORPH/build/libs/GAssert-1.0-SNAPSHOT-all.jar
if [[ -f "$GASSERT_JAR" ]]; then
    echo "  $GASSERT_JAR already present, skip"
else
    cd "$GENMORPH"
    export JAVA_HOME=$JAVA8
    export PATH=$JAVA_HOME/bin:$PATH
    ./gradlew shadowJar --quiet
fi

cd "$REPO_ROOT"

echo ""
echo "=== Setup complete ==="
echo "  JAVA_HOME    = $JAVA8"
echo "  GENMORPH     = $GENMORPH"
echo "  GASSERT_JAR  = $GASSERT_JAR"
echo "  S5_ROOT      = $REPO_ROOT"
echo ""
echo "Next: bash $REPO_ROOT/scripts/run_all.sh"
