#!/usr/bin/env bash
# bootstrap.sh — Provision Ubuntu 22.04 for the S5 aligned pilot.
#
# Run this once at the start of a Claude Code Remote session. It:
#   1. installs OS packages (jdk-8 / jdk-11 / maven / python deps)
#   2. downloads + unzips GenMorph Zenodo replication package
#   3. sets up env vars (writes to ~/.bashrc-genmorph for re-sourcing)
#   4. compiles GenMorph SUT classes via gradle (caches Gradle distro)
#   5. runs Python pip install
#
# Expected runtime: 5-10 min on a fresh Ubuntu container (depending on
# apt cache + network for Zenodo download).
#
# Usage:
#   bash bootstrap.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Step 0 — Sanity check: are we on Ubuntu?
# ---------------------------------------------------------------------------
if ! command -v apt-get >/dev/null; then
    echo "ERROR: apt-get not found. This script targets Ubuntu/Debian."
    echo "       For other distributions, install equivalent packages manually."
    exit 1
fi

OS_VER=$(lsb_release -ds 2>/dev/null || cat /etc/os-release | grep PRETTY_NAME | head -1)
echo "[0/5] Detected OS: $OS_VER"

# ---------------------------------------------------------------------------
# Step 1 — Install OS packages
# ---------------------------------------------------------------------------
echo "[1/5] Installing OS packages (apt-get)..."
sudo apt-get update -y
sudo apt-get install -y \
    openjdk-8-jdk \
    openjdk-11-jdk \
    maven \
    python3-pip \
    python3-venv \
    wget unzip git curl ca-certificates

# Verify Java installations
JAVA8_PATH=/usr/lib/jvm/java-8-openjdk-amd64
JAVA11_PATH=/usr/lib/jvm/java-11-openjdk-amd64

if [[ ! -d "$JAVA8_PATH" ]]; then
    echo "WARN: $JAVA8_PATH not found; trying to locate JDK 8 alternative"
    JAVA8_PATH=$(find /usr/lib/jvm -maxdepth 1 -type d -name "*8*" | head -1)
    [[ -z "$JAVA8_PATH" ]] && { echo "FATAL: no JDK 8 found"; exit 2; }
fi
if [[ ! -d "$JAVA11_PATH" ]]; then
    JAVA11_PATH=$(find /usr/lib/jvm -maxdepth 1 -type d -name "*11*" | head -1)
    [[ -z "$JAVA11_PATH" ]] && { echo "FATAL: no JDK 11 found"; exit 2; }
fi
echo "  JDK 8 :  $JAVA8_PATH"
echo "  JDK 11:  $JAVA11_PATH"

# ---------------------------------------------------------------------------
# Step 2 — Download GenMorph Zenodo package
# ---------------------------------------------------------------------------
echo "[2/5] Downloading GenMorph Zenodo replication package..."
mkdir -p /tmp/genmorph_pilot
cd /tmp/genmorph_pilot

ZENODO=https://zenodo.org/records/10067096/files
for ZIPFILE in evaluation.zip mrs.zip genmorph.zip; do
    if [[ -f "$ZIPFILE" ]]; then
        echo "  $ZIPFILE already downloaded; skip"
    else
        echo "  fetching $ZIPFILE..."
        wget --no-check-certificate -nc "$ZENODO/$ZIPFILE" || {
            echo "ERROR: download failed for $ZIPFILE."
            echo "       Try manually:  curl -L -o $ZIPFILE \"$ZENODO/$ZIPFILE\""
            exit 3
        }
    fi
done

echo "  unzipping into target layout..."
[[ -d evaluation ]] || (unzip -o -q evaluation.zip -d evaluation_unzip && mv evaluation_unzip evaluation)
[[ -d mrs ]]        || (unzip -o -q mrs.zip        -d mrs_unzip        && mv mrs_unzip        mrs)
[[ -d genmorph_full ]] || (unzip -o -q genmorph.zip -d genmorph_unzip && mv genmorph_unzip genmorph_full)

# Sanity: required files present
REQUIRED_FILES=(
    "/tmp/genmorph_pilot/genmorph_full/genmorph/build/libs/GAssert-1.0-SNAPSHOT-all.jar"
    "/tmp/genmorph_pilot/genmorph_full/genmorph/pitest-wrapper-1.7.4.jar"
    "/tmp/genmorph_pilot/genmorph_full/genmorph/configs/math-sut/src/main/java/MathClass.java"
    "/tmp/genmorph_pilot/mrs/mrs/assertions_seed11/MathClass?gcd?0/MathClass?gcd?0@MR0.jir.txt"
    "/tmp/genmorph_pilot/evaluation/evaluation/pitest_seed11/MathClass?gcd?0/mutants_killed.csv"
)
for f in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: required file missing after unzip: $f"
        exit 4
    fi
done
echo "  all expected files present in /tmp/genmorph_pilot/"

# ---------------------------------------------------------------------------
# Step 3 — Write env file (source from ~/.bashrc or in run_all.sh)
# ---------------------------------------------------------------------------
echo "[3/5] Writing env-file ~/.bashrc-genmorph ..."
cat > "$HOME/.bashrc-genmorph" <<EOF
# Auto-generated by bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export JAVA8=$JAVA8_PATH
export JAVA11=$JAVA11_PATH
export JAVA_HOME=\$JAVA11
export PATH=\$JAVA_HOME/bin:\$PATH

export GENMORPH=/tmp/genmorph_pilot/genmorph_full/genmorph
export EVOSUITE_HOME=\$GENMORPH
export EVOSUITE_JAR=evosuite-1.1.0.jar
export RANDOOP_HOME=\$GENMORPH
export RANDOOP_JAR=randoop-all-4.3.0.jar
export PITEST_HOME=\$GENMORPH
export PITEST_JAR=pitest-wrapper-1.7.4.jar
EOF

# Ensure it gets sourced in interactive shells
if ! grep -q "bashrc-genmorph" "$HOME/.bashrc" 2>/dev/null; then
    echo '[ -f ~/.bashrc-genmorph ] && source ~/.bashrc-genmorph' >> "$HOME/.bashrc"
fi
source "$HOME/.bashrc-genmorph"

# ---------------------------------------------------------------------------
# Step 4 — Compile SUT (caches gradle distro for later runs)
# ---------------------------------------------------------------------------
echo "[4/5] Pre-compiling GenMorph SUT (caches gradle dependencies)..."
cd "$GENMORPH"
if [[ -f gradlew ]]; then
    chmod +x gradlew
    JAVA_HOME=$JAVA8 ./gradlew --version 2>&1 | tail -3 || {
        echo "WARN: gradle bootstrap failed; upstream may need JDK 8 specifically for build"
    }
else
    echo "WARN: $GENMORPH/gradlew not found; skipping gradle bootstrap"
fi

# ---------------------------------------------------------------------------
# Step 5 — Python deps
# ---------------------------------------------------------------------------
echo "[5/5] Installing Python deps..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PILOT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
pip3 install --user -r "$PILOT_ROOT/requirements.txt" || {
    echo "WARN: pip install had issues; ensure ~/.local/bin is on PATH for any --user wheels"
}

echo ""
echo "=== bootstrap.sh complete ==="
echo "Next: bash verify_env.sh"
