#!/usr/bin/env python3
"""
Set G (GenMorph seed11) detection baseline — READ-ONLY extraction.

WHAT THIS IS
------------
A faithful extraction of the **Set G** (GenMorph GP-evolved MRs, seed 11) kill
data from GenMorph upstream's *already published* evaluation package
(`evaluation/pitest_seed11/<subject>/mutants_killed.csv`, the rows whose
EXPERIMENT column equals `assertions_seed11`).

WHAT THIS IS *NOT*
------------------
This is NOT the full §6.6 aligned comparison. **Set N is not evaluated here.**
Evaluating Set N requires per-execution `states` + `classifications` (absent
from the Zenodo package) regenerated by a functional Stage-1 pipeline. The
repository's `scripts/run_all.sh` is non-functional (interface mismatch with
the GenMorph upstream toolchain — see ISSUES/003-run-all-pipeline-broken.md),
so Set N detection cannot be produced in this environment. Every `set_n_*`
field below is therefore a structural placeholder (zero), NOT a measured zero.

PROVENANCE / HONESTY
--------------------
Set G numbers are adopted *as published upstream*; they are NOT locally
recomputed/aligned (the alignment step the task asks for needs the same broken
pipeline). As an internal self-consistency check we recompute each subject's
union over its `assertions_seed11` MR rows and assert it equals upstream's
pre-aggregated `assertions_seed11,*` row.

Output (under setg_baseline/):
  seed11/<subject>/mutants_killed.csv   filtered seed11 Set G rows (+ header)
  seed11/<subject>/aligned_metrics.json produced by the repo's parse_results.py
  setg_baseline_summary.json            pooled Set G kill rate + Wilson 95% CI
"""

import csv
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM_PITEST = Path("/tmp/genmorph_pilot/evaluation/pitest_seed11")
UPSTREAM_MRS = Path("/tmp/genmorph_pilot/mrs/assertions_seed11")
OUT_ROOT = REPO / "setg_baseline"
SEED_TAG = "assertions_seed11"


def wilson_ci(k, n, z=1.96):
    """Wilson score interval (same formula as scripts/aggregate_metrics.py)."""
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = (z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


def filter_subject_csv(src_csv, out_csv):
    """Keep header + EXPERIMENT==assertions_seed11 real-MR rows (MR != '*').

    Returns (n_mutants, n_setg_mr_rows, recomputed_kills, star_row_count_or_None).
    """
    with open(src_csv, newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        m_cols = [i for i, c in enumerate(header) if c.startswith("M") and c[1:].isdigit()]
        kept, star_count = [], None
        for row in reader:
            if row[0] != SEED_TAG:
                continue
            if row[1] == "*":
                star_count = int(row[-1])
            else:
                kept.append(row)
    # recompute union over the real MR rows
    n_mut = len(m_cols)
    union = [0] * n_mut
    for row in kept:
        for j, ci in enumerate(m_cols):
            if int(row[ci]):
                union[j] = 1
    recomputed_kills = sum(union)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with open(out_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(kept)
    return n_mut, len(kept), recomputed_kills, star_count


def main():
    if not UPSTREAM_PITEST.is_dir():
        sys.exit(f"FATAL: upstream package not found at {UPSTREAM_PITEST} — run setup.sh first")

    empty_setn = Path(tempfile.mkdtemp(prefix="empty_setn_"))  # forces all MRs -> Set G
    subjects = sorted(p.name for p in UPSTREAM_PITEST.iterdir() if p.is_dir())

    per_subject = []
    total_mut = total_kills = total_eff_mrs = total_dsl_mrs = 0
    missing, no_valid_mr = [], []

    for s in subjects:
        src_csv = UPSTREAM_PITEST / s / "mutants_killed.csv"
        dsl_dir = UPSTREAM_MRS / s
        n_dsl = len(list(dsl_dir.glob("*.jor.txt"))) if dsl_dir.is_dir() else 0
        out_dir = OUT_ROOT / "seed11" / s

        if not src_csv.is_file():
            missing.append(s)
            per_subject.append({
                "subject": s, "status": "missing_mutants_killed_csv",
                "n_mutants": None, "setg_kills": None, "setg_kill_rate": None,
                "setg_effective_mrs": 0, "setg_total_mrs_dsl": n_dsl,
            })
            continue

        n_mut, n_rows, kills, star = filter_subject_csv(src_csv, out_dir / "mutants_killed.csv")
        # carry the upstream status file along (FP info for per-MR detail)
        src_status = UPSTREAM_PITEST / s / "mrs_status.csv"
        if src_status.is_file():
            shutil.copy(src_status, out_dir / "mrs_status.csv")

        # self-consistency check vs upstream's pre-aggregated union row
        if star is not None and kills != star:
            sys.exit(f"FATAL self-consistency break for {s}: union={kills} != upstream '*' row={star}")

        # produce familiar-schema artifact via the repo's TESTED parser
        cmd = [sys.executable, str(REPO / "scripts" / "parse_results.py"),
               "--csv", str(out_dir / "mutants_killed.csv"),
               "--set-n-dir", str(empty_setn),
               "--output", str(out_dir / "aligned_metrics.json")]
        if (out_dir / "mrs_status.csv").is_file():
            cmd += ["--status", str(out_dir / "mrs_status.csv")]
        subprocess.run(cmd, check=True, capture_output=True, text=True)

        with open(out_dir / "aligned_metrics.json") as f:
            am = json.load(f)
        assert am["set_g"]["n_killed"] == kills, f"parser/union disagree for {s}"

        if n_rows == 0:
            no_valid_mr.append(s)
        eff = am["set_g"]["n_effective_mrs"]  # MRs that actually kill >=1 mutant (a CSV row may have COUNT=0)
        total_mut += n_mut
        total_kills += kills
        total_eff_mrs += eff
        total_dsl_mrs += n_dsl
        per_subject.append({
            "subject": s,
            "status": "ok" if n_rows > 0 else "no_valid_setg_mr_in_seed11",
            "n_mutants": n_mut,
            "setg_kills": kills,
            "setg_kill_rate": kills / n_mut if n_mut else None,
            "setg_effective_mrs": eff,
            "setg_total_mrs_dsl": n_dsl,
            "setg_effective_mr_ratio_dsl": eff / n_dsl if n_dsl else None,
            "union_matches_upstream_star_row": (star is None) or (kills == star),
        })

    lo, hi = wilson_ci(total_kills, total_mut)
    summary = {
        "experiment": "Set G (GenMorph seed11) DETECTION BASELINE ONLY",
        "is_full_aligned_comparison": False,
        "set_n_status": ("NOT EVALUATED — requires states/classifications (absent from Zenodo "
                          "package) + a functional Stage-1 pipeline. run_all.sh is non-functional "
                          "(see ISSUES/003-run-all-pipeline-broken.md). All set_n_* fields are "
                          "placeholders, NOT measured zeros."),
        "provenance": ("Adopted as-published from upstream evaluation/pitest_seed11/<subject>/"
                       "mutants_killed.csv (EXPERIMENT==assertions_seed11, MR!='*'). NOT locally "
                       "recomputed/aligned. Self-consistency check: per-subject union == upstream "
                       "'assertions_seed11,*' row (passed for all subjects with data)."),
        "n_subjects_benchmark": len(subjects),
        "n_subjects_with_setg_data": len(subjects) - len(missing),
        "subjects_missing_data": missing,
        "subjects_no_valid_setg_mr_seed11": no_valid_mr,
        "total_mutants": total_mut,
        "set_g": {
            "kills": total_kills,
            "kill_rate": total_kills / total_mut if total_mut else 0.0,
            "wilson_95_ci": [lo, hi],
            "effective_mrs_killing_ge1": total_eff_mrs,
            "total_mrs_dsl": total_dsl_mrs,
            "effective_mr_ratio_dsl": total_eff_mrs / total_dsl_mrs if total_dsl_mrs else None,
        },
        "set_n": None,
        "paired_mcnemar": None,
        "per_subject": per_subject,
        "caveats": [
            "Pooling treats each mutant as an independent Bernoulli trial; this underestimates "
            "variance (mutants within a subject share SUT/inputs/mutator).",
            "GuavaClass?join?0 has no upstream seed11 mutants_killed.csv -> excluded from the "
            "pooled denominator; reported as missing (underpowered).",
            "capitalize/acos/millerRabinPrimeTest have zero seed11 Set G MRs surviving upstream's "
            "FP filter -> Set G kills=0 is a real upstream outcome, not a parsing artifact.",
            "Effective-MR ratio uses the DSL-dir MR count as denominator; the per-subject "
            "aligned_metrics.json effective_mr_ratio (parse_results.py) uses CSV-row count instead.",
        ],
    }
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    with open(OUT_ROOT / "setg_baseline_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    # console report
    print(f"n_subjects={len(subjects)}  with_data={len(subjects)-len(missing)}  "
          f"missing={missing}")
    print(f"no_valid_setg_mr_seed11={no_valid_mr}")
    print(f"Set G (seed11): {total_kills}/{total_mut} = {summary['set_g']['kill_rate']:.4f} "
          f"Wilson95% [{lo:.4f}, {hi:.4f}]  effMR(DSL)={total_eff_mrs}/{total_dsl_mrs}")
    print(f"Set N: NOT EVALUATED (pipeline broken; see ISSUES/003)")
    shutil.rmtree(empty_setn, ignore_errors=True)


if __name__ == "__main__":
    main()
