"""
Set L: five MRs generated by GPT-4 prompted with the SE(3)-equivariant
point-cloud testing task description.

The prompt and raw LLM output are recorded in `prompt_log.md`
(generated 2026-05-15 UTC against `gpt-4-turbo-2024-04-09` at
temperature=0.0 with seed=4246, via the `run_gpt4_prompt.py` driver).
The five MRs below are direct translations of the LLM's JSON output
into Python callables, preserving the LLM's stated tolerances (1e-5)
and input/output relations verbatim.

The set composition is exactly what an unprompted-by-NOETHER tester
would receive from GPT-4 for this task: three equivariance-style MRs
(rotation, translation, permutation) plus two robustness-style MRs
(scaling, noise). Overlap with Set N's `rho_rot` (rotation invariance)
is expected and is itself a data point reported in the manuscript.

JSON specs (verbatim from `prompt_log.md::Raw GPT-4 output`):

  - L_rot:        rotation_invariance      (tolerance 1e-5)
  - L_trans:      translation_invariance   (tolerance 1e-5)
  - L_scale:      scaling_robustness       (tolerance 1e-5)
  - L_perm:       permutation_invariance   (tolerance 1e-5)
  - L_noise:      noise_robustness         (tolerance 1e-5)
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mr_interface import MR, MRResult


# GPT-4's specified tolerance for fp32 architectures (verbatim across all
# five MRs). NOETHER's tau for rho_rot is 1e-4; the LLM proposed 1e-5,
# which is tighter than NOETHER and represents the LLM-tester's choice.
TAU = 1e-5


# -----------------------------------------------------------------------------
# L_rot: rotation_invariance
#   input_relation: apply an arbitrary SE(3) rotation matrix to every point
#   output_relation: probability distribution remains nearly identical
# -----------------------------------------------------------------------------

def _llm_rot_fn(model, point_cloud, *, num_samples: int = 16, seed: int = 100) -> MRResult:
    """Rotation invariance per GPT-4 spec L_rot (overlap with N's rho_rot)."""
    rng = np.random.default_rng(seed)
    p_orig = np.asarray(model.predict(point_cloud))
    max_dev = 0.0
    for _ in range(num_samples):
        a = rng.standard_normal((3, 3))
        q, _ = np.linalg.qr(a)
        if np.linalg.det(q) < 0:
            q[:, 0] = -q[:, 0]
        rotated = np.asarray(point_cloud) @ q.T
        dev = float(np.max(np.abs(p_orig - np.asarray(model.predict(rotated)))))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_rot — rotation_invariance per GPT-4 (overlap with N's rho_rot)")


# -----------------------------------------------------------------------------
# L_trans: translation_invariance
#   input_relation: apply an arbitrary translation vector to all points
#   output_relation: output remains nearly the same
# -----------------------------------------------------------------------------

def _llm_trans_fn(model, point_cloud, *, num_samples: int = 16, seed: int = 101) -> MRResult:
    """Translation invariance per GPT-4 spec L_trans."""
    rng = np.random.default_rng(seed)
    p_orig = np.asarray(model.predict(point_cloud))
    max_dev = 0.0
    for _ in range(num_samples):
        t = rng.standard_normal(3)
        translated = np.asarray(point_cloud) + t
        dev = float(np.max(np.abs(p_orig - np.asarray(model.predict(translated)))))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_trans — translation_invariance per GPT-4 (T^3 subgroup of SE(3))")


# -----------------------------------------------------------------------------
# L_scale: scaling_robustness
#   input_relation: multiply each coordinate by a constant scaling factor
#   output_relation: output probability changes only within numerical tolerance
# -----------------------------------------------------------------------------

def _llm_scale_fn(model, point_cloud, *, alphas=(1.2,)) -> MRResult:
    """Scaling robustness per GPT-4 spec L_scale.

    Note: per GPT-4's own rationale, scaling is *not* strictly enforced by
    SE(3)-equivariance and is therefore out-of-scope under NOETHER's
    A_equi (no operator in O corresponds to a global scaling map). Set L
    includes it to represent that the unprompted-by-NOETHER tester's
    realism gap: LLM testers commonly emit scale-robustness MRs because
    scaling is a generic ML testing reflex.
    """
    p_orig = np.asarray(model.predict(point_cloud))
    max_dev = 0.0
    for a in alphas:
        scaled = a * np.asarray(point_cloud)
        p_scaled = np.asarray(model.predict(scaled))
        dev = float(np.max(np.abs(p_orig - p_scaled)))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_scale — scaling_robustness per GPT-4 (out-of-scope under A_equi)")


# -----------------------------------------------------------------------------
# L_perm: permutation_invariance
#   input_relation: randomly shuffle the order of the rows (points)
#   output_relation: output remains unchanged
# -----------------------------------------------------------------------------

def _llm_perm_fn(model, point_cloud, *, num_samples: int = 8, seed: int = 102) -> MRResult:
    """Permutation invariance per GPT-4 spec L_perm (overlap with N's rho_perm)."""
    rng = np.random.default_rng(seed)
    pc = np.asarray(point_cloud)
    p_orig = np.asarray(model.predict(pc))
    max_dev = 0.0
    for _ in range(num_samples):
        perm = rng.permutation(pc.shape[0])
        permuted = pc[perm]
        dev = float(np.max(np.abs(p_orig - np.asarray(model.predict(permuted)))))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_perm — permutation_invariance per GPT-4 (S_n subgroup; overlap with N's rho_perm)")


# -----------------------------------------------------------------------------
# L_noise: noise_robustness
#   input_relation: add zero-mean Gaussian noise (std 0.01) to each coordinate
#   output_relation: output differs only minimally from unperturbed input
# -----------------------------------------------------------------------------

def _llm_noise_fn(model, point_cloud, *, sigma: float = 0.01, num_samples: int = 8, seed: int = 103) -> MRResult:
    """Noise robustness per GPT-4 spec L_noise.

    Out-of-scope under NOETHER's A_equi: small Gaussian perturbations
    are not a group action on X. The LLM-tester would typically emit
    this MR because robustness to measurement noise is a generic ML
    testing reflex; NOETHER correctly classifies it as outside the
    operator-algebraic substrate.
    """
    rng = np.random.default_rng(seed)
    pc = np.asarray(point_cloud)
    p_orig = np.asarray(model.predict(pc))
    max_dev = 0.0
    for _ in range(num_samples):
        delta = sigma * rng.standard_normal(pc.shape)
        p_pert = np.asarray(model.predict(pc + delta))
        dev = float(np.max(np.abs(p_orig - p_pert)))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_noise — noise_robustness per GPT-4 (out-of-scope under A_equi)")


# -----------------------------------------------------------------------------
# Set L registry
# -----------------------------------------------------------------------------

SET_L: list[MR] = [
    MR(name="L_rot",   block="G",     set_label="L", fn=_llm_rot_fn),
    MR(name="L_trans", block="G",     set_label="L", fn=_llm_trans_fn),
    MR(name="L_scale", block="(out)", set_label="L", fn=_llm_scale_fn),
    MR(name="L_perm",  block="G",     set_label="L", fn=_llm_perm_fn),
    MR(name="L_noise", block="(out)", set_label="L", fn=_llm_noise_fn),
]


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from model_interface import StubModel  # type: ignore[import-not-found]
    model = StubModel(equivariant_break=False)
    rng = np.random.default_rng(42)
    pc = rng.standard_normal((128, 3))
    print("Set L (GPT-4 generated, 2026-05-15) on baseline stub:")
    for mr in SET_L:
        r = mr.evaluate(model, pc)
        print(f"  {mr.name:8s} block={mr.block:6s} holds={r.holds!s:6s} dev={r.deviation:.3e}")
