"""
Set L: five MRs generated by GPT-4 prompted with the SE(3)-equivariant
point-cloud testing task description.

The prompt and raw LLM output are recorded in `prompt_log.md`. The human
author translates each JSON spec into a callable below. Until the LLM
generation has been run, the placeholder MRs use plausible "what an
unprompted tester might write" implementations matching the typical
shape of GPT-4 output for this prompt.

PLACEHOLDER STATUS: the five entries below are *expected-shape*
placeholders. Replace each `_placeholder_*_fn` with the actual MR
translated from `prompt_log.md::Raw GPT-4 output` once the LLM run has
been executed. Documented overlap with Set N is acceptable and is itself
a data point reported in the manuscript.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mr_interface import MR, MRResult


TAU = 1e-3  # LLM-default tolerance (typically looser than NOETHER's 1e-4)


# -----------------------------------------------------------------------------
# Placeholder MR 1: rotation invariance (anticipated overlap with NOETHER)
# -----------------------------------------------------------------------------

def _placeholder_rot_fn(model, point_cloud, *, num_samples: int = 16, seed: int = 100) -> MRResult:
    """Rotation invariance — a near-certain GPT-4 first answer."""
    rng = np.random.default_rng(seed)
    p_orig = np.asarray(model.predict(point_cloud))
    max_dev = 0.0
    for _ in range(num_samples):
        a = rng.standard_normal((3, 3))
        q, _ = np.linalg.qr(a)
        if np.linalg.det(q) < 0:
            q[:, 0] = -q[:, 0]
        rotated = np.asarray(point_cloud) @ q.T
        dev = float(np.max(np.abs(p_orig - np.asarray(model.predict(rotated)))))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= TAU), deviation=max_dev,
                    notes="L_rot — anticipated overlap with N's rho_rot")


# -----------------------------------------------------------------------------
# Placeholder MR 2: small-perturbation robustness (Lipschitz-style)
# -----------------------------------------------------------------------------

def _placeholder_perturb_fn(model, point_cloud, *, eps: float = 0.01, seed: int = 101) -> MRResult:
    """Adversarial-style robustness within an epsilon-ball."""
    rng = np.random.default_rng(seed)
    pc = np.asarray(point_cloud)
    p_orig = np.asarray(model.predict(pc))
    max_dev = 0.0
    for _ in range(8):
        delta = eps * rng.standard_normal(pc.shape)
        p_pert = np.asarray(model.predict(pc + delta))
        dev = float(np.max(np.abs(p_orig - p_pert)))
        if dev > max_dev:
            max_dev = dev
    # Looser tolerance reflects realistic robustness claim
    return MRResult(holds=(max_dev <= 0.05), deviation=max_dev,
                    notes="L_perturb — small-perturbation robustness (out of NOETHER scope)")


# -----------------------------------------------------------------------------
# Placeholder MR 3: per-class probability validity
# -----------------------------------------------------------------------------

def _placeholder_prob_valid_fn(model, point_cloud, **_) -> MRResult:
    """Probabilities must be in [0,1] and sum to 1."""
    p = np.asarray(model.predict(point_cloud))
    in_range = bool(np.all(p >= -TAU) and np.all(p <= 1 + TAU))
    sums_to_one = bool(abs(p.sum() - 1.0) <= TAU)
    holds = in_range and sums_to_one
    return MRResult(
        holds=holds,
        deviation=max(abs(p.sum() - 1.0), float(max(0.0, -p.min()))),
        notes="L_prob_valid — basic probability validity (likely trivial)",
    )


# -----------------------------------------------------------------------------
# Placeholder MR 4: scaling robustness
# -----------------------------------------------------------------------------

def _placeholder_scale_fn(model, point_cloud, *, alphas=(0.5, 0.75, 1.25, 2.0)) -> MRResult:
    """Output should be insensitive to uniform scaling of input.

    Note: this MR is *not* a true equivariance for a SE(3)-equivariant
    classifier, since global scaling is not in SO(3). LLMs commonly emit
    this MR because scaling-robustness is a generic ML testing reflex.
    NOETHER would correctly reject it as out-of-scope (no operator in
    A_equi corresponds to it); set L includes it to represent that
    realism gap.
    """
    p_orig = np.asarray(model.predict(point_cloud))
    max_dev = 0.0
    for a in alphas:
        scaled = a * np.asarray(point_cloud)
        p_scaled = np.asarray(model.predict(scaled))
        dev = float(np.max(np.abs(p_orig - p_scaled)))
        if dev > max_dev:
            max_dev = dev
    return MRResult(holds=(max_dev <= 0.05), deviation=max_dev,
                    notes="L_scale — out-of-scope under NOETHER but typical LLM output")


# -----------------------------------------------------------------------------
# Placeholder MR 5: deterministic re-evaluation
# -----------------------------------------------------------------------------

def _placeholder_determ_fn(model, point_cloud, **_) -> MRResult:
    """Same input twice -> same output (anticipated overlap with rho_train)."""
    p1 = np.asarray(model.predict(point_cloud))
    p2 = np.asarray(model.predict(point_cloud))
    dev = float(np.max(np.abs(p1 - p2)))
    return MRResult(holds=(dev <= TAU), deviation=dev,
                    notes="L_determ — anticipated overlap with N's rho_train")


# -----------------------------------------------------------------------------
# Set L registry
# -----------------------------------------------------------------------------
# IMPORTANT: replace these placeholders with the actual GPT-4 output once
# prompt_log.md::Raw GPT-4 output has been filled in.

SET_L: list[MR] = [
    MR(name="L_rot",        block="G",     set_label="L", fn=_placeholder_rot_fn),
    MR(name="L_perturb",    block="(out)", set_label="L", fn=_placeholder_perturb_fn),
    MR(name="L_prob_valid", block="(out)", set_label="L", fn=_placeholder_prob_valid_fn),
    MR(name="L_scale",      block="(out)", set_label="L", fn=_placeholder_scale_fn),
    MR(name="L_determ",     block="L*",    set_label="L", fn=_placeholder_determ_fn),
]


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from model_interface import StubModel  # type: ignore[import-not-found]
    model = StubModel(equivariant_break=False)
    rng = np.random.default_rng(42)
    pc = rng.standard_normal((128, 3))
    print("Set L on baseline stub:")
    for mr in SET_L:
        r = mr.evaluate(model, pc)
        print(f"  {mr.name:14s} block={mr.block:6s} holds={r.holds!s:6s} dev={r.deviation:.3e}")
